name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - app-router
      - pages-router
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: pnpm install --loglevel=error --ignore-scripts
      - run: pnpm lint -- --max-warnings 0
